
  return nameUser.trim().charAt(index);


return nameUser.trim().charAt(index);

  return nameUser.trim().charAt(index);






  return nameUser.trim().charAt(index);


return nameUser.trim().charAt(index);

  return nameUser.trim().charAt(index);




}



  return nameUser.trim().charAt(index);


return nameUser.trim().charAt(index);

  return nameUser.trim().charAt(index);






  return nameUser.trim().charAt(index);


return nameUser.trim().charAt(index);

  return nameUser.trim().charAt(index);


